#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-sensormux.h"
#include "hitechnic-gyro.h"

const tMUXSensor HTGYRO = msensor_S2_1;

task main()
{
	float rotSpeed = 0;
	float heading = 0;

	// Calibrate the gyro, make sure you hold the sensor still
	HTGYROstartCal(HTGYRO);

	// Reset the timer.
	time1[T1] = 0;

	while (true)
	{
		// Wait until 20ms has passed
		while (time1[T1] < 20)
			wait1Msec(1);

		// Reset the timer
		time1[T1]=0;

		rotSpeed = HTGYROreadRot(HTGYRO);


		heading += rotSpeed * 0.02;

		// Display our current heading on the screen
		nxtDisplayCenteredBigTextLine(3, "%2.0f", heading);
	}

}
