#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     GYRO_MUX,       sensorI2CCustom)
#pragma config(Sensor, S3,     SENSOR_MUX,     sensorI2CCustom)
#pragma config(Sensor, S4,     angle_sensor,   sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     right_motor,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     left_motor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     block_lift_motor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     block_lift_motor2, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     sky_hook,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    grabber_right,        tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    grabber_left,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    roger_slide,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    optical_servo,        tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    ground_arm,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    abdd,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
*
*  @file auto.c
*
*  @brief The automatic program for the robot.
*
*  @copyright Copyright 2013, Got Robot? FTC Team 5037
*
*/

/*Includes*/

//-----------------------
// sensor/mux/joystick includes
//-----------------------

#include "joystickdriver.c"
#include "lib/xander/hitechnic-sensormux.h"
#include "lib/xander/lego-light.h"
#include "lib/xander/hitechnic-irseeker-v2.h"
#include "lib/xander/hitechnic-gyro.h"
#include "lib/xander/hitechnic-angle.h"
#include "lib/xander/hitechnic-accelerometer.h"
#include "lib/xander/hitechnic-eopd.h"

//-----------------------
// Custom include
//-----------------------

#include "lib/compile_flags.h"
#include "lib/global_variables.h"
#include "lib/abs_initialize.h"
#include "lib/abs_s1_mission_execute.h"
#include "lib/abs_s2_mission_execute.h"
#include "lib/abs_s3_mission_execute.h"
#include "lib/abs_s4_mission_execute.h"
#include "lib/abs_s5_mission_execute.h"
#include "lib/abs_s6_mission_execute.h"
#include "lib/abs_dlog.h"
#include "lib/abs_end_ramp.h"
#include "lib/abs_stay_on_ramp.h"
#define DRIVE_TYPE = TANK
//========================================
// Main program
//========================================
task main()
{
	abs_initialize();
	abs_drive(FORWARD, E_TIME, 2000, 100, true, NON_SENSOR);
	abs_drive(BACKWARD, E_TIME, 2000, 100, true, NON_SENSOR);
	abs_drive(FORWARD, E_DEGREES, 360, 100, true, NON_SENSOR);
	abs_drive(BACKWARD, E_DEGREES, 360, 100, true, NON_SENSOR);
	abs_turn(CLOCKWISE, POINT, TURN, 180, 60);
	abs_turn(COUNTERCLOCKWISE, POINT, TURN, 180, 60);
}
