#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     SENSOR_MUX,     sensorI2CCustom)
#pragma config(Sensor, S3,     GYRO_MUX,       sensorI2CCustom)
#pragma config(Sensor, S4,     angle_sensor,   sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     right_motor,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left_motor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    goal_claw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
*
*  @file auto.c
*
*  @brief The automatic program for the robot.
*
*  @copyright Copyright 2013, Got Robot? FTC Team 5037
*
*/

/*Includes*/

//-----------------------
// sensor/mux/joystick includes
//-----------------------

#include "joystickdriver.c"
#include "lib/xander/hitechnic-sensormux.h"
#include "lib/xander/lego-light.h"
#include "lib/xander/hitechnic-irseeker-v2.h"
#include "lib/xander/hitechnic-gyro.h"
#include "lib/xander/hitechnic-angle.h"
#include "lib/xander/hitechnic-accelerometer.h"
#include "lib/xander/hitechnic-eopd.h"

//-----------------------
// Custom include
//-----------------------

#include "lib/compile_flags.h"
#include "lib/global_variables.h"
#include "lib/abs_initialize.h"
#include "lib/abs_IR_center_read.h"
#include "lib/abs_dlog.h"
#include "lib/abs_stay_on_ramp.h"
#include "lib/abs_drive.h"
#include "lib/abs_turn.h"
#include "lib/abs_ramp_mission.h"
#include "lib/abs_floor_mission.h"
#define DRIVE_TYPE = TANK

//========================================
// Main program
//========================================
task main()
{
	Delete(LogFileName, LogIoResult);
	OpenWrite(LogFileHandle, LogIoResult, LogFileName, LogFileSize);

	abs_dlog(__FILE__ ,"Program start"," Start time:", nPgmTime);

	abs_initialize();

	switch(g_input_array[STARTING_POINT])
	{
	case 1: abs_ramp_mission(); break;
	case 2: abs_floor_mission(); break;
	}

	wait1Msec(STARTING_DELAY*1000);

	//abs_second_objective(SECOND_ROLLGOAL1);

	//switch()
	//{

	//}

	//StartTask(abs_IR_center_read);

	//abs_drive(FORWARD, E_ANGLE, 300, 80, true, GYRO);

	//abs_drive(FORWARD, E_ANGLE, 243, 80, true, GYRO);
	//abs_drive(BACKWARD, E_ANGLE, 12, 80, true, GYRO);

	//abs_turn(COUNTERCLOCKWISE, POINT, TURN, 20, 60);

	//while(true)
	//{}
	//	if(nNxtButtonPressed == kLeftButton)
	//	{
	//		motor[right_motor] = 60;
	//		motor[left_motor] = 60;
	//	}

	//abs_turn(CLOCKWISE, POINT, TURN, 360, 60);
	//abs_turn(COUNTERCLOCKWISE, POINT, TURN_TO, 0, 50);


	//abs_drive(BACKWARD, E_TIME, 2000, 100, true, NON_SENSOR);
	//abs_drive(FORWARD, E_DEGREES, 360, 100, true, NON_SENSOR);
	//abs_drive(BACKWARD, E_DEGREES, 360, 100, true, NON_SENSOR);
	//abs_turn(CLOCKWISE, POINT, TURN, 180, 60);
	//abs_turn(COUNTERCLOCKWISE, POINT, TURN, 180, 60);

	abs_turn(CLOCKWISE, POINT, TURN, 20, 60);
	abs_drive(BACKWARD, E_ANGLE, 305, 100, true, GYRO);
	abs_turn(CLOCKWISE, POINT, TURN, 40, 60);
	abs_drive(BACKWARD, E_ANGLE, 15, 100, true, GYRO);
	abs_turn(COUNTERCLOCKWISE, POINT, TURN, 60, 60);
	abs_drive(BACKWARD, E_ANGLE, 61, 100, true, GYRO);

	abs_dlog(__FILE__ ,"end auto", "End time:", nPgmTime);
	Close(LogFileHandle, LogIoResult);
}
