#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task left()
{
	while(true)
	{
		if(nNxtButtonPressed==kLeftButton)
		{
			servo[servo1] = 255;
			//servo[servo2] = 0;
		}
		else if(nNxtButtonPressed==kRightButton)
		{
			servo[servo1] = 0;
			//servo[servo2] = 255;
		}
		else if(nNxtButtonPressed==kEnterButton)
		{
			servo[servo1] = 127;
			//servo[servo2] = 127;
		}
	}
}

task main()
{
	servoChangeRate(servo1)=1;
	servoChangeRate(servo2)=1;

	StartTask(left);

	while(true)
	{
		if(nNxtButtonPressed==kLeftButton)
		{
			//servo[servo1] = 255;
			servo[servo2] = 0;
		}
		else if(nNxtButtonPressed==kRightButton)
		{
			//servo[servo1] = 0;
			servo[servo2] = 255;
		}
		else if(nNxtButtonPressed==kEnterButton)
		{
			//servo[servo1] = 127;
			servo[servo2] = 127;
		}
	}
}
